-- Conky, a system monitor https://github.com/brndnmtthws/conky
--
-- This configuration file is Lua code. You can write code in here, and it will
-- execute when Conky loads. You can use it to generate your own advanced
-- configurations.
--
-- Try this (remove the `--`):
--
-- print("Loading Conky config")
--
-- For more on Lua, see:
-- https://www.lua.org/pil/contents.html
--
-- Conky Lua API: https://conky.cc/lua

-- Configuration settings: https://conky.cc/config_settings
conky.config = {
   background = true,
   double_buffer = true,
   lua_draw_hook_post = 'conky_cairo_circle_charts',  -- The function name has to start with `conky_`.
   lua_load = './charts.lua',
   minimum_height = 1624,  -- On wayland this is Resolution/Scale: 2160/1.33 with Scale=133%
   minimum_width = 3849,  -- On wayland this is Resolution/Scale: 5120/1.33 with Scale=133%
   out_to_wayland = true,
   out_to_x = false,
   update_interval = 1.0,
}

-- Variables: https://conky.cc/variables
conky.text = [[

]]
